package(default_visibility = ["//visibility:public"])

cc_library(
    name = "status",
    srcs = [
        "status.cc",
    ],
    hdrs = [
        "status.h",
    ],
    deps = [
        "//common/proto:cc_status_proto",
        "//common/utils/common:defines",
        "@glog//:glog",
    ],
)

