package(default_visibility = ["//visibility:public"])

cc_library(
    name = "agents",
    srcs = ["agents.cc"],
    hdrs = ["agents.h"],
    deps = [
    	"//pnc/agents/hongfz16:hongfz16_agent",
        "//pnc/agents/sample:sample_agent",
        "//pnc/simulation:vehicle_agent_factory",
    ],
    alwayslink = 1,
)
