package(default_visibility = ["//visibility:public"])

cc_library(
    name = "image_header",
    hdrs = ["image.h"],
    deps = [
        "//common/utils/common:defines",
        "@glog//:glog",
    ],
)

