package(default_visibility = ["//visibility:public"])

cc_library(
    name = "context",
    hdrs = ["context.h"],
    deps = [
        "//common/utils/gl:context_and_functions",
        "@glog//:glog",
        "@qt//:qt_gui",
    ],
)

