package(default_visibility = ["//visibility:public"])

cc_library(
    name = "map_lib",
    hdrs = ["map_lib.h"],
    data = [
        "//homework5/map/grid2:grid2_map",
    ],
    deps = [
        "//common/utils/file:file",
        "//common/proto:cc_map_proto",
        "@glog",
    ],
)

