package(default_visibility = ["//visibility:public"])

cc_library(
	name="sepGround",
	srcs=["sepGround.cc"],
	hdrs=["sepGround.h"],
	deps=[
		"//homework2:pointcloud",
	]
)

cc_library(
	name="GridUtils",
	srcs=["GridUtils.cc"],
	hdrs=["GridUtils.h"],
	deps=[
		"//homework2:pointcloud",
	]
)

cc_library(
	name="CorrTrans",
	srcs=["CorrTrans.cc"],
	hdrs=["CorrTrans.h"],
	deps=[
		"//homework2:pointcloud",
	]
)