package(default_visibility = ["//visibility:public"])

cc_library(
	name="FeatureExtract",
	srcs=["FeatureExtract.cc"],
	hdrs=[
		"FeatureExtract.h",
		"RTree.h"
	],
	deps=[
        "@eigen//:eigen",
		"//homework2:pointcloud",
	]
)