package(default_visibility = ["//visibility:public"])

cc_library(
    name = "libdynamic",
    srcs = ["libdynamic.so"],
    hdrs = ["lib_vehicle_status_model_solver.h"],
    deps = [
        "//common/proto:cc_control_proto",
        "//common/proto:cc_vehicle_params_proto",
        "//common/proto:cc_vehicle_status_proto",
    ],
)
