package(default_visibility = ["//visibility:public"])

cc_library(
    name = "array_view",
    hdrs = [
        "array_view.h",
    ],
    deps = [
        "//common/utils/common:defines",
        "@glog//:glog",
    ],
)

cc_library(
    name = "fixed_array",
    hdrs = [
        "fixed_array.h",
    ],
    deps = [
        "//common/utils/common:defines",
        "@glog//:glog",
    ],
)

cc_library(
    name = "utils",
    hdrs = [
        "utils.h",
    ],
    deps = [
        "@glog//:glog",
    ],
)

