package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "simulation_main",
    srcs = ["simulation_main.cc"],
    deps = [
        "//homework6/display:simulation_main_window",
        "@gflags//:gflags",
        "@glog",
    ],
)
