package(default_visibility = ["//visibility:public"])

cc_library(
    name = "grid_index",
    hdrs = [
        "grid_index.h",
        "grid_index.hpp",
    ],
    deps = [
        "//common/utils/math",
    ],
)

