package(default_visibility = ["//visibility:public"])

cc_binary(
	name="ExtractTrainingFeatures",
	srcs=["ExtractTrainingFeatures.cc"],
	deps=[
		"//perception/FeatureExtract:FeatureExtract",
		"//homework4:obstacle_extract",
        "//common/utils/file:file",
	]
)