package(default_visibility = ["//visibility:public"])

cc_library(
    name = "agents",
    hdrs = ["agents.h"],
    srcs = ["agents.cc"],
    deps = [
        "//homework6/agents/sample:sample_agent",
        "//homework6/simulation:vehicle_agent_factory",
        "//homework6/agents/myagent:hongfz_agent",
    ],
    alwayslink = 1,
)
