package(default_visibility = ["//visibility:public"])

cc_library(
    name = "hungarian_sparse",
    srcs = ["hungarian_sparse.cc"],
    hdrs = ["hungarian_sparse.h"],
    deps = [
        "//common/utils/common:defines",
        "//common/utils/containers:fixed_array",
        "@glog//:glog",
    ],
)
