package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "main",
    srcs = ["ChessboardDistort.cc"],
    deps = [
    	"@myopencv//:opencv"
        #"@opencv//:core",
        #"@opencv//:highgui",
    ],
)
